language: python
python:
  - "2.7"

install:
  - pip install ansible==1.9.1
  - pip install ansible-lint
  - "printf '[defaults]\\nroles_path = ../' > ansible.cfg"

before_script:
#  - echo localhost > inventory
#  - ansible-galaxy install --role-file requirements.yml

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test_role.yml --syntax-check
  # lint for good measure
  - ansible-lint tests/test_role.yml
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test_role.yml --connection=local --sudo
  # Check role idempotency
  - >
    ansible-playbook -i tests/inventory tests/test_role.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
